/*
 Generated by typeshare 1.13.3
*/

/** A 2D vector with double-precision floating point components */
export interface DVec2 {
	x: number;
	y: number;
}

/** A 3D vector with double-precision floating point components */
export interface DVec3 {
	x: number;
	y: number;
	z: number;
}

export interface EdgeInfo {
	curve_details: CurveDetails;
	orientation: Orientation;
}

export interface WireInfo {
	edges: EdgeInfo[];
	is_outer: boolean;
}

export interface FaceInfo {
	surface_details: SurfaceDetails;
	surface_type: string;
	wires: WireInfo[];
}

export interface SolidInfo {
	faces: FaceInfo[];
}

export interface StepInfo {
	solids: SolidInfo[];
}

