/*
 Generated by typeshare 1.13.3
*/

/** A B-Spline curve profile */
export interface BSplineCurveProfile {
	nb_poles: number;
	degree: number;
	is_rational: boolean;
	is_periodic: boolean;
	knots: number[];
	multiplicities: number[];
}

/** A 3D vector with double-precision floating point components */
export interface Vector3 {
	x: number;
	y: number;
	z: number;
}

/** A B-Spline curve */
export interface BSplineCurve {
	profile: BSplineCurveProfile;
	poles: Vector3[];
	weights?: number[];
	first_parameter: number;
	last_parameter: number;
}

/** A B-Spline surface */
export interface BSplineSurface {
	u_profile: BSplineCurveProfile;
	v_profile: BSplineCurveProfile;
	poles: Vector3[][];
	weights?: number[][];
}

/** A Bezier curve profile */
export interface BezierCurveProfile {
	nb_poles: number;
	degree: number;
}

/** A Bezier curve */
export interface BezierCurve {
	profile: BezierCurveProfile;
	poles: Vector3[];
	weights?: number[];
	first_parameter: number;
	last_parameter: number;
}

/** A Bezier surface */
export interface BezierSurface {
	u_profile: BezierCurveProfile;
	v_profile: BezierCurveProfile;
	poles: Vector3[][];
	weights?: number[][];
}

/** A circle */
export interface Circle {
	center: Vector3;
	axis: Vector3;
	x_axis: Vector3;
	y_axis: Vector3;
	radius: number;
	first_parameter: number;
	last_parameter: number;
}

/** A conical surface */
export interface Cone {
	location: Vector3;
	axis_location: Vector3;
	axis_direction: Vector3;
	x_direction: Vector3;
	y_direction: Vector3;
	ref_radius: number;
	semi_angle: number;
}

/** A cylindrical surface */
export interface Cylinder {
	location: Vector3;
	axis_location: Vector3;
	axis_direction: Vector3;
	x_direction: Vector3;
	y_direction: Vector3;
	radius: number;
}

/** Detailed information about a curve's geometric properties */
export type CurveDetails = 
	/** A line */
	| { type: "Line", data: Line }
	/** A circle */
	| { type: "Circle", data: Circle }
	/** An ellipse */
	| { type: "Ellipse", data: Ellipse }
	/** A B-Spline curve */
	| { type: "BSplineCurve", data: BSplineCurve }
	/** A Bezier curve */
	| { type: "BezierCurve", data: BezierCurve }
	/** A hyperbola */
	| { type: "Hyperbola", data: Hyperbola }
	/** A parabola */
	| { type: "Parabola", data: Parabola }
	/** An offset curve */
	| { type: "OffsetCurve", data: OffsetCurve }
	/** A trimmed curve */
	| { type: "TrimmedCurve", data: TrimmedCurve }
	/** Unknown or unsupported curve type */
	| { type: "Unknown", data: string };

/** The orientation of a topological shape (edge, face, etc.) */
export enum Orientation {
	/** Forward orientation - the default positive direction */
	Forward = "Forward",
	/** Reversed orientation - the opposite direction */
	Reversed = "Reversed",
	/** Internal orientation - internal to a solid */
	Internal = "Internal",
	/** External orientation - external to a solid */
	External = "External",
}

export interface EdgeInfo {
	id: number;
	curve: CurveDetails;
	orientation: Orientation;
}

/** An ellipse */
export interface Ellipse {
	center: Vector3;
	axis: Vector3;
	x_axis: Vector3;
	y_axis: Vector3;
	major_radius: number;
	minor_radius: number;
	first_parameter: number;
	last_parameter: number;
}

/** Detailed information about a surface's geometric properties */
export type SurfaceDetails = 
	/** A planar surface */
	| { type: "Plane", data: Plane }
	/** A cylindrical surface */
	| { type: "Cylinder", data: Cylinder }
	/** A conical surface */
	| { type: "Cone", data: Cone }
	/** A spherical surface */
	| { type: "Sphere", data: Sphere }
	/** A toroidal surface */
	| { type: "Torus", data: Torus }
	/** A B-Spline surface */
	| { type: "BSpline", data: BSplineSurface }
	/** A Bezier surface */
	| { type: "Bezier", data: BezierSurface }
	/** Unknown or unsupported surface type */
	| { type: "Unknown", data: string };

export interface WireInfo {
	edges: EdgeInfo[];
	is_outer: boolean;
}

export interface FaceInfo {
	surface: SurfaceDetails;
	wires: WireInfo[];
}

/** A hyperbola */
export interface Hyperbola {
	center: Vector3;
	axis: Vector3;
	major_radius: number;
	minor_radius: number;
}

/** A line */
export interface Line {
	origin: Vector3;
	direction: Vector3;
	first_parameter: number;
	last_parameter: number;
}

/** An offset curve */
export interface OffsetCurve {
	basis_curve_type: string;
	offset: number;
}

/** A parabola */
export interface Parabola {
	vertex: Vector3;
	axis: Vector3;
	focal: number;
}

/** UV parameter bounds for a face */
export interface UVBounds {
	u_min: number;
	u_max: number;
	v_min: number;
	v_max: number;
}

/** A planar surface */
export interface Plane {
	location: Vector3;
	axis_location: Vector3;
	axis_direction: Vector3;
	x_direction: Vector3;
	y_direction: Vector3;
	/** UV parameter bounds of the face (not the infinite plane) */
	bounds: UVBounds;
}

export interface SolidInfo {
	faces: FaceInfo[];
}

/** A spherical surface */
export interface Sphere {
	location: Vector3;
	axis_location: Vector3;
	axis_direction: Vector3;
	x_direction: Vector3;
	y_direction: Vector3;
	radius: number;
}

export interface StepInfo {
	solids: SolidInfo[];
}

/** A toroidal surface */
export interface Torus {
	location: Vector3;
	axis_location: Vector3;
	axis_direction: Vector3;
	x_direction: Vector3;
	y_direction: Vector3;
	major_radius: number;
	minor_radius: number;
}

/** A trimmed curve */
export interface TrimmedCurve {
	basis_curve_type: string;
	first_parameter: number;
	last_parameter: number;
}

/** A 2D vector with double-precision floating point components */
export interface Vector2 {
	x: number;
	y: number;
}

