[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+exception-handling"]

[target.wasm32-unknown-emscripten]
linker = "emcc"
ar = "emar"
runner = "emrun"

rustflags = [
    "-C",
    "link-arg=-sENVIRONMENT=web",
    "-C",
    "link-arg=-sALLOW_MEMORY_GROWTH=1",
    "-C",
    "link-arg=-sMODULARIZE=1",
    "-C",
    "link-arg=-sEXPORT_ES6=1",
    "-C",
    "link-arg=-sEXPORT_NAME='createStepParserModule'",
    "-C",
    "link-arg=-sEXPORTED_RUNTIME_METHODS=[\"UTF8ToString\",\"cwrap\",\"ccall\",\"HEAPU8\"]",
    "-C",
    "link-arg=-sEXPORTED_FUNCTIONS=[\"_malloc\",\"_free\",\"_parse_step\",\"_free_step\"]",
]

[env]
# Enable C++ exceptions for WASM builds
CXXFLAGS = "-fexceptions"
