[package]
name = "occt-interop"
description = "Interop crate for OpenCascade"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
typeshare = "1.0"
glam = { version = "0.24", optional = true }

[features]
default = ["glam"]
glam = ["dep:glam"]
